use_frameworks!

platform :ios, '9.0'

target 'SFCountdownButton_Example' do
  pod 'SFCountdownButton', :path => '../'

  target 'SFCountdownButton_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
